version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/html/web-20210222-repo
permissions:
    - object: /var/www/html/web-20210222-repo
      pattern: "**"
      owner: apache
      group: apache
      mode: 755
      type:
        - file
hooks:
    BeforeInstall:
     - location: scripts/initialize.sh
       runas: root
